__version__ = '0.1.18'
__title__ = "FileCrawler"
__description__ = "File Crawler index files and search hard-coded credentials."
__url__ = "https://github.com/helviojunior/filecrawler"
__build__ = 0x63c974a8
__author__ = "Helvio Junior  (M4v3r1ck)"
__author_email__ = "helvio.junior@sec4us.com.br"
__license__ = "GPL-3.0"
__copyright__ = "Copyright Helvio Junior"
